apiVersion:  sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: scheduled-job-dv-ping-source
spec:
  schedule: "*/5 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: scheduled-job-dv-service