apiVersion: v1
kind: Template
metadata:
  name: scheduled-job-dv-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app-env-config
  data:
    BROKER_URL : '<IP_POT_ARTEMIS>'
    BROKER_PORT : '61616'
    BROKER_USER : 'artemis'
    BROKER_PWD : 'simetraehcapa'
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: broker-sub
  spec:
    replicas: 1
    selector: 
      name: broker-sub
    template:
      metadata:
        labels:
          name: broker-sub
      spec:
        containers:
        - image: docker.io/neclaes/subscriber:latest
          name: subscriber
          ports:
          - containerPort: 8012
          env:
            - name: BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: BROKER_URL
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: BROKER_PORT
            - name: BROKER_USER
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: BROKER_USER
            - name: BROKER_PWD
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: BROKER_PWD 