kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "nc-vatvalidationservice-build" 
spec:
  source: 
    git:
      uri: "https://github.com/NeClaes/Stage"
      contextDir: vat_validation_service_knative 
  output: 
    to:
      kind: "ImageStreamTag"
      name: "nc-vatvalidationservice:latest"