apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nc-vatvalidation-service
spec:
  template:
    spec:
      containers:
        source: 
          git:
            uri: "https://github.com/NeClaes/Stage"
            contextDir: vat_validation_service_knative
        output: 
          to:
            kind: "ImageStreamTag"
            name: "nc-vatvalidationservice:latest"
        strategy:
          type: "Docker"
          dockerStrategy:
            from:
              kind: "ImageStreamTag"
              name: "node:12-slim" 
        env:
        - name: RESPONSE
          value: "Hello Serverless!"
        - name: SERVER_VALUES_PORT
          valueFrom:
            configMapKeyRef:
              name: server-values
              key: PORT
