apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nc-vatvalidation-service
spec:
  template:
    spec:
      containers:
        - image: <link of imageStream>
          env:
          - name: RESPONSE
            value: "Hello Serverless!"
          - name: SERVER_VALUES_PORT
            valueFrom:
              configMapKeyRef:
                name: server-values
                key: PORT
           
